### ISSUE TITLE
 https://t.me/muenchentraktor isn't longer accesible?

### ISSUE THREAD

**Issue by drozel** [trisch-me/muenchen-wiki#91]
Привет. Присоединился к каналу и буквально через минуту "sorry this chat isn't longer accessible". 
Меня залочили? Почему?

**Comment by ivanmilov** [comment]
может, капча была, и на неё не последовало ответа?

**Comment by drozel** [comment]
@ivanmilov не видел, среди последних сообщений в чате не было

**Comment by ivanmilov** [comment]
ну бот то за собой подчищает. Подожди, пока модераторы это прочтут, может, впустят :)

**Comment by trisch-me** [comment]
@drozel там бот стоит вначале против спама. если просто зайти и не пройти капчу, то он автоматом банит.
я разбанила, попробуй еще раз
